[package]
name = "mouse_coords"
version = "0.1.0"
authors = ["ostrosco <ostrosco@fastmail.fm>"]
build = "build.rs"

[dependencies]

[build-dependencies]
pkg-config = "*"

[dependencies.x11]
version = "2.17.2"
features = ["xlib"]
